Fix/remove unnecessary ui components
social-dist0rtion-protocol/planet-a pull request #13
Opened 2019-07-17 13:22 UTC by TimDaub

TODOs:

- [x] all links to the "Exchange.js" view. Ideally remove Exchange.js
- [x] RequestFunds.js and "Request" button in App.js
- [ ] In "Advanced", hide "Display currency" and "Enable advanced features"
- [ ] Adjust "Code" and "About" in "Advanced" (actually make them configurable with config.js and send a PR upstream <3)
- [ ] Adjust <title /> and all other meta tags/data in index.html

2019-07-17 14:10 UTC, MaxStalker commented
I'm starting a review process now.

2019-07-17 22:56 UTC, MaxStalker requested changes
Looking good! Aside small thing with display prop :)

2019-07-17 22:56 UTC, MaxStalker commented on src/components/SendToAddress.js
> +          <Field style={{display: "none"}} mb={3} label={messageText}>
Since this is rimble - you can simply use ```display="none"``` here instead of inlinening styles

2019-07-17 23:11 UTC, MaxStalker commented
I was also wondering - do we really need address field here, when we first arrive on this screen?
![image](https://user-images.githubusercontent.com/3136647/61417573-2d807c00-a900-11e9-824b-445049022941.png)

Also, I would recommend to remove "Scan QR code" button, then skip all extra steps and open camera for scanning right away, like if we press that it. Cause noone gonna bother entering address by hand anyway :)

2019-07-18 12:19 UTC, TimDaub commented
> Also, I would recommend to remove "Scan QR code" button, then skip all extra steps and open camera for scanning right away, like if we press that it. Cause noone gonna bother entering address by hand anyway :)

That's a pretty controversial change of the UI in my opinion and I'm sure I could collect multiple points on why I believe it's problematic. Additionally, it's not within the scope of this PR. Of course, if you want to move this forward, feel free to open an issue on a repository where you see fit!

2019-07-18 13:46 UTC, MaxStalker approved these changes
All good :)

2019-07-18 14:26 UTC, merged